module UsersHelper

def gravatar_for(user, size: 40)
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.name, class: "gravatar")
end

end

# In this helper, a gravatar_id is generated by taking the hash (MD5 hash) of the
# email address of the user (converted to lowercase to avoid having duplicate
# email addresses with different cases).
#
# Then a url is generated to connect to the gravatar.
#
# Finally, an image is generated (using the image_tag helper), the image’s
# source is the gravatar’s url generated using the gravatar id.
# The image has a class that is called “gravatar” to style it.
